version: "3"
services:
  back-end:
    container_name: back-end-springRest
    image: spring-boot-rest-docker
    ports:
       - "8008:8008"
    environment:
       - spring.datasource.username=aziz
       - spring.datasource.password=skikenaziz
       - spring.datasource.url=jdbc:mysql://mysqlspringboot/newdb
      
    depends_on:
       - mysqlspringboot
       
   

  mysqlspringboot:
    container_name: mysql-db-springRest
    image: mysql:5
    expose:
       - "3306"
    environment:
       - MYSQL_PASSWORD=skikenaziz
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=newdb  
       - MYSQL_USER=aziz
       - MySQL_HOST=% 
    ports:
       - "3306:3306"
    
 
  front-end:
    image: angular-app:v1
    container_name: front-end-springRest
    ports:
      - 80:80
    depends_on:
      - back-end
    
      
    
